### PR TITLE
Updating travis for Puppet 4

### PR DESCRIPTION
**Pull request by jaxxstorm**

### CODE REVIEW

**Comment by richardc** [comment]
Can you figure out why this is failing?

**Comment by jaxxstorm** [comment]
The problem was that rake is deprecated for ruby 1.8.7, and some of the sensu gems aren't supported on ruby > 2. I've pinned the version of ruby to 1.8.7 until you're ready to stop support and also updated the travis matrix so we're not testing older puppet versions on modern rubies.

Let me know if this is okay?

**Comment by richardc** [comment]
I think it's better to just drop ruby 1.8 testing against all the puppet 3 cells; it's not a supported configuration.

**Comment by jaxxstorm** [comment]
So just yank `rvm: 1.8.7` altogether?

**Comment by cyberious** [comment]
I'd say 👍 to removing 1.8.7 as Puppet Enterprise 3.8 is EOL this December and it was even running 1.9.3

**Pull request closed without merging**
